version: 2

project_name: gacc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gacc
    # 저장소를 현재 프로젝트인 soongeo/gacc 로 지정합니다.
    repository:
      owner: soongeo
      name: gacc

    # GitHub 루트가 아닌 Formula 폴더 하위에 설정 파일을 만들도록 지정
    directory: Formula
    
    # 릴리즈 시 추가될 커밋 메시지 형식
    commit_msg_template: "brew: update formula for {{ .ProjectName }} version {{ .Tag }}"

    # Homebrew Formula 설치 스크립트 작성
    install: |-
      bin.install "gacc"
      
      # [선택] Cobra를 통한 자동완성을 지원한다면 아래의 주석을 푸세요
      # output = Utils.popen_read("#{bin}/gacc completion bash")
      # (bash_completion/"gacc").write output
      # output = Utils.popen_read("#{bin}/gacc completion zsh")
      # (zsh_completion/"_gacc").write output
