version: 1

project_name: gacc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: gacc
    # Distribute the formula to the current project repo (soongeo/gacc)
    repository:
      owner: soongeo
      name: gacc

    # Place the formula configuration inside the Formula directory instead of the repo root.
    directory: Formula
    
    # Commit message format used when publishing the formula.
    commit_msg_template: "brew: update formula for {{ .ProjectName }} version {{ .Tag }}"

    # Homebrew Formula installation script
    install: |-
      bin.install "gacc"
      
      # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
      output = Utils.popen_read("#{bin}/gacc completion bash")
      (bash_completion/"gacc").write output
      output = Utils.popen_read("#{bin}/gacc completion zsh")
      (zsh_completion/"_gacc").write output
