# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gacc < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/soongeo/gacc/releases/download/v0.1.2/gacc_Darwin_x86_64.tar.gz"
      sha256 "105f46b4732e565d2a3ef4caf20878716fd0e2424f4add484f0a53945f3a14ce"

      def install
        bin.install "gacc"

        # [선택] Cobra를 통한 자동완성을 지원한다면 아래의 주석을 푸세요
        # output = Utils.popen_read("#{bin}/gacc completion bash")
        # (bash_completion/"gacc").write output
        # output = Utils.popen_read("#{bin}/gacc completion zsh")
        # (zsh_completion/"_gacc").write output
      end
    end
    on_arm do
      url "https://github.com/soongeo/gacc/releases/download/v0.1.2/gacc_Darwin_arm64.tar.gz"
      sha256 "5da3858870b76f1d003085dd044712babe29f3b456f1f7c98ab8864748e9c2d6"

      def install
        bin.install "gacc"

        # [선택] Cobra를 통한 자동완성을 지원한다면 아래의 주석을 푸세요
        # output = Utils.popen_read("#{bin}/gacc completion bash")
        # (bash_completion/"gacc").write output
        # output = Utils.popen_read("#{bin}/gacc completion zsh")
        # (zsh_completion/"_gacc").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.1.2/gacc_Linux_x86_64.tar.gz"
        sha256 "8bb4fa516d390b71f9213c4096e05794f2f164311eef9af64694c5fe9ad65c06"

        def install
          bin.install "gacc"

          # [선택] Cobra를 통한 자동완성을 지원한다면 아래의 주석을 푸세요
          # output = Utils.popen_read("#{bin}/gacc completion bash")
          # (bash_completion/"gacc").write output
          # output = Utils.popen_read("#{bin}/gacc completion zsh")
          # (zsh_completion/"_gacc").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.1.2/gacc_Linux_arm64.tar.gz"
        sha256 "3466035699b5ef92c938c3cd4d55c4a053ec99b02403e1dbed1a4295db0492ff"

        def install
          bin.install "gacc"

          # [선택] Cobra를 통한 자동완성을 지원한다면 아래의 주석을 푸세요
          # output = Utils.popen_read("#{bin}/gacc completion bash")
          # (bash_completion/"gacc").write output
          # output = Utils.popen_read("#{bin}/gacc completion zsh")
          # (zsh_completion/"_gacc").write output
        end
      end
    end
  end
end
