# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gacc < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/soongeo/gacc/releases/download/v0.2.0/gacc_Darwin_x86_64.tar.gz"
      sha256 "064d2be40ca7742a5f53a4ffae45401ecd587305a52c8c69c48b0843c3ea8a32"

      def install
        bin.install "gacc"

        # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
        output = Utils.popen_read("#{bin}/gacc completion bash")
        (bash_completion/"gacc").write output
        output = Utils.popen_read("#{bin}/gacc completion zsh")
        (zsh_completion/"_gacc").write output
      end
    end
    on_arm do
      url "https://github.com/soongeo/gacc/releases/download/v0.2.0/gacc_Darwin_arm64.tar.gz"
      sha256 "76fa5a82e3d2d05a4d2b3211c947324cb9802dad54bcc564afe7f52762d7cb5c"

      def install
        bin.install "gacc"

        # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
        output = Utils.popen_read("#{bin}/gacc completion bash")
        (bash_completion/"gacc").write output
        output = Utils.popen_read("#{bin}/gacc completion zsh")
        (zsh_completion/"_gacc").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.2.0/gacc_Linux_x86_64.tar.gz"
        sha256 "26ce049379ddd8e394415e8d235f8aad189aece9af3963cfe455c338b973a768"

        def install
          bin.install "gacc"

          # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
          output = Utils.popen_read("#{bin}/gacc completion bash")
          (bash_completion/"gacc").write output
          output = Utils.popen_read("#{bin}/gacc completion zsh")
          (zsh_completion/"_gacc").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.2.0/gacc_Linux_arm64.tar.gz"
        sha256 "94afa3581195cf6521f2ba8276f569d2641b2f31687d8476f17325b4fd1c8e65"

        def install
          bin.install "gacc"

          # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
          output = Utils.popen_read("#{bin}/gacc completion bash")
          (bash_completion/"gacc").write output
          output = Utils.popen_read("#{bin}/gacc completion zsh")
          (zsh_completion/"_gacc").write output
        end
      end
    end
  end
end
