# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gacc < Formula
  desc ""
  homepage ""
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/soongeo/gacc/releases/download/v0.1.4/gacc_Darwin_x86_64.tar.gz"
      sha256 "f03239021af4db814972a07675fe882d1c68a5fa6132c8f739120a59b6bed967"

      def install
        bin.install "gacc"

        # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
        output = Utils.popen_read("#{bin}/gacc completion bash")
        (bash_completion/"gacc").write output
        output = Utils.popen_read("#{bin}/gacc completion zsh")
        (zsh_completion/"_gacc").write output
      end
    end
    on_arm do
      url "https://github.com/soongeo/gacc/releases/download/v0.1.4/gacc_Darwin_arm64.tar.gz"
      sha256 "b58a89a13d9dff2e6b86564540fce641f1bdb76baf16e93ad9f7bea27103746e"

      def install
        bin.install "gacc"

        # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
        output = Utils.popen_read("#{bin}/gacc completion bash")
        (bash_completion/"gacc").write output
        output = Utils.popen_read("#{bin}/gacc completion zsh")
        (zsh_completion/"_gacc").write output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.1.4/gacc_Linux_x86_64.tar.gz"
        sha256 "38cbea2151f7002b78f50f799bf575490a038ec66bafa4bb3dbed5976fee3937"

        def install
          bin.install "gacc"

          # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
          output = Utils.popen_read("#{bin}/gacc completion bash")
          (bash_completion/"gacc").write output
          output = Utils.popen_read("#{bin}/gacc completion zsh")
          (zsh_completion/"_gacc").write output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soongeo/gacc/releases/download/v0.1.4/gacc_Linux_arm64.tar.gz"
        sha256 "c32e7206c612931150ae7412d972f566c22b5860e90b420d7c64f9a12ffcfd4d"

        def install
          bin.install "gacc"

          # Automatically generate and register Cobra autocomplete files (installed automatically on brew install)
          output = Utils.popen_read("#{bin}/gacc completion bash")
          (bash_completion/"gacc").write output
          output = Utils.popen_read("#{bin}/gacc completion zsh")
          (zsh_completion/"_gacc").write output
        end
      end
    end
  end
end
